version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/ai_matching
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: job-matching-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local